version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 25
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "fs-extra"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    rebase-strategy: "auto"
    commit-message:
      prefix: fix
      prefix-development: chore
