---
version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  version: 2

  test-and-release:
    jobs:
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
              node_version:
                - latest
                - lts
                - v16 #developed with
      - release-management/release-package:
          context: context-validator-ci
          dryrun: false
          github-release: true
          node_version: v16
          post-job-steps:
            - run: yarn global add @armakuni/circleci-context-validator@latest
            - run: ccv circleci validate --context-definitions .circleci/context_validator.yml
          filters:
            branches:
              only: main
          requires:
            - release-management/test-package-lts-linux
            - release-management/test-package-latest-linux
            - release-management/test-package-v16-linux

