---
version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4.37.0

workflows:
  version: 2

  test-and-release:
    jobs:
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
              node_version:
                - latest
                - lts
                - v16 #developed with
                - v14
      - release-management/release-package:
          dryrun: true
          github-release: true
          filters:
            branches:
              only: main
          requires:
            - release-management/test-package-lts-linux
            - release-management/test-package-latest-linux
            - release-management/test-package-v16-linux
            - release-management/test-package-v14-linux


  dependabot-automerge:
    triggers:
      - schedule:
          cron: '0 2,5,8,11 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/dependabot-automerge:
          context: context-validator-ci
